# Site settings
title: "Daniel Hervás Rodao"
SEOtitle: "Daniel Hervás Rodao · Student"
description: "I'm a Telematis Engineering student at King's Juan Carlos University."
url: ""
baseurl: ""
lang: en
logo: "/assets/images/logo.png"
favicon: "/assets/images/favicon.png"
logo: "/assets/images/logo.png"
name_img: "/assets/images/RaulSanMartin.png"
author: "Daniel Hervás Rodao"
permalink: /:categories/:title/
theme: null # https://github.com/jekyll/jekyll/issues/7478#issuecomment-454346783
timezone: Europe/Madrid
include: [".well-known"] # dat:// protocol support

# Top bar
topbar: "<b>Daniel Hervás Rodao</b> / dhrodao"

# Liquid
liquid:
  error_mode: strict

# Markdown
markdown: kramdown

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-paginate

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Paginate blog
paginate: 10
paginate_path: "/blog/page:num"

# Categories and tags pages
tag_page: '/tags/'
category_page: '/categories/'

# Addons
google-site-verification: "4KpPIPbUzRNI1DJR-OrOS5tNYrNvTIMj2Xh9bIybdPE"

# Social settings (you can use Font Awesome icons [fa fa-icon] or Iconmonstr ones [im im-icon])
email: hello@[this domain]

social:
  - title: e-mail
    description: '<span class="email-address">hello@[this domain]</span> for e-mail'
    link: "/contact"
    alt: "Contact page"
  - title: github
    description: "dhrodao on GitHub"
    link: "https://github.com/dhrodao"
    alt: "dhrodao's GitHub profile"
  - title: linkedin
    description: "Daniel Hervás Rodao on Linkedin"
    link: "https://www.linkedin.com/in/danielhervasrodao"
    alt: "dhrodao's Linkedin profile"
